### ISSUE TITLE
Results on Long Range Arena

### ISSUE THREAD

**Issue by joaogui1** [mlpen/Nystromformer#1]
Hi, I saw the [tweet](https://twitter.com/tanmingxing/status/1359301186734620675?s=20) about this paper and wanted to know the performance of Nystromformer on each individual task in Long Range Arena. (Also what is the "Standard" in the graph posted? Standard transformer does much worse in LRA)

**Comment by yyxiongzju** [comment]
Hi @joaogui1,

Thanks for your interest. We did not release the score on each individual task in LRA benchmark. When we update the draft by adding it, I will ping you here. Standard denotes the standard self-attention. Since the LRA contains several tasks, the average score, 58.95 vs 58.77, indicates Nystr\"{o}mformer is competitive to standard self-attention on LRA tasks.

**Comment by joaogui1** [comment]
Thanks for the answers @yyxiongzju, but on [the original LRA](https://openreview.net/pdf?id=qVyeW-grC2k) Transformer scores 54.39, not 58.77, why the difference?
Also, any predictions on when will you release the next version?

**Comment by yyxiongzju** [comment]
Hi @joaogui1, here are the scores on each individual task in LRA benchmark. 
![LRA](https://user-images.githubusercontent.com/20729758/107904374-3c327900-6f11-11eb-94f4-fbb516dd4c97.png).

The difference is from the performance of running all models on the Retrieval task in LRA benchmark. We followed the LRA procedure to generate tokens/labels to run experiments on the Retrieval task. 1, download [LRA dataset](https://storage.googleapis.com/long-range-arena/lra_release.gz); 2, use their [code](https://github.com/google-research/long-range-arena) generate tokens/labels. With the generated tokens/labels, we ran all the models on the Retrieval task and it showed higher performance than the original LRA reported. We will release our PyTorch code for running all tasks of LRA benchmark on 02/17. 

We will update our paper before 03/02, which is the camera-ready submission deadline of AAAI 2021.

**Comment by mlpen** [comment]
We released the source code for LRA benchmark. For retrieval task, [LRA repo](https://github.com/google-research/long-range-arena) suggested that we need to download the actual documents from http://aan.how/download/ as they cannot re-distribute this dataset and only released the dataset with a format `label paper1_id paper2_id` without textual data. However, we found that the released [lra_release.gz](https://storage.googleapis.com/long-range-arena/lra_release.gz) already contained the textual data, so we directly used the code from `long-range-arena/lra_benchmarks/matching/input_pipeline.py` to generate datasets.
