### ISSUE TITLE
Question about LRA Pathfinder task

### ISSUE THREAD

**Issue by YJHMITWEB** [mlpen/Nystromformer#12]
Thanks for your great work.

I noticed that in the paper and also in this repo, you report the results on LRA tasks. I am trying to train your model on LRA with the code given in this repo. For the Pathfinder task, I follow the dataset preparing guidance and I get 3 sets of pickle files, e.g. pathfinder32-curv_baseline, pathfinder32-curv_contour_length_9, and pathfinder32-curv_contour_length_14, each with train/dev/test splits.

I would like to know that which set gives the 70.94 result in table 3.

**Comment by yyxiongzju** [comment]
Thanks for your interest in our work.

We used pathfinder32-curv_contour_length_14 for achieving 70.94 in table 3.

**Comment by YJHMITWEB** [comment]
Thanks.
