### ISSUE TITLE
Length of Text Classification Task of LRA

### ISSUE THREAD

**Issue by lxchtan** [mlpen/Nystromformer#13]
Hello, I noticed that in your paper, Table 3 shown the Text (4K).
However, max_length was set to 1000 in your code LRA/datasets/text.py.
Is the Text task length 4K or 1K for the scores given in Table 3?

**Comment by yyxiongzju** [comment]
Hi lxchtan,

Thanks for your interest. It is the 4K sequence length for the scores in Table 3.

**Comment by lxchtan** [comment]
Thanks for your kindly reply.
