### ISSUE TITLE
Lemma 1 parenthesis seem wrong

### ISSUE THREAD

**Issue by thomasw21** [mlpen/Nystromformer#2]
Hello, first of all great work! This looks very promising.

As I'm reading a bit more in depth, I'm wondering if you might have an error on parenthesis in lemma 1. Both the code, and the  proof seem to indicate it. 

![image](https://user-images.githubusercontent.com/24695242/107854218-d49a0200-6e1a-11eb-9e75-5d2207d9cff1.png)

The last term should apply only to `AZ` instead of `(15I - AZ)` no?

This would "fix" the following lines in the proof

![image](https://user-images.githubusercontent.com/24695242/107854276-35c1d580-6e1b-11eb-8af3-cb78a1196480.png)

**Comment by yyxiongzju** [comment]
Hi @thomasw21, Thanks for the nice catch. I will update it.

**Comment by alex26-research** [comment]
> Hi @thomasw21, Thanks for the nice catch. I will update it.

Hi. Thank u for Nystromformer. Will be code for keras/tensorflow?

**Comment by yyxiongzju** [comment]
Hi @alex26-research, the code is just for PyTorch now.
