### ISSUE TITLE
Pre-trained weights

### ISSUE THREAD

**Issue by NielsRogge** [mlpen/Nystromformer#4]
Hi,

Thank you for this very clean repository! I wonder whether any checkpoints will be released? If yes, I'm interested in adding those to the HuggingFace Transformers library (the Reformer and LongFormer are already there, but the Linformer and the Nystromformer aren't yet). Since we only have to replace the self-attention mechanism, this seems quite straightforward in terms of modeling. 

Kind regards,

Niels

**Comment by yyxiongzju** [comment]
Hi @NielsRogge, Thanks for your interest in Nystromformer. We are pretty packed recently for ICCV submission. We will release the checkpoint after the submission deadline. It will be great if you can help add to the HuggingFace Transformers.

**Comment by yyxiongzju** [comment]
Hi @NielsRogge , Thanks for your interest. I just finished some submissions. Here is the pretrained [Nystromformer model](https://www.dropbox.com/s/8uv4f6q52oaqwkh/Nystromformer.model?dl=0) on BookCorpus plus English Wikipedia for sequence length 512. I wonder if you can help add to the HuggingFace Transformers?

**Comment by NielsRogge** [comment]
Sure I can help! Do you have an email address to set up a Slack channel?

**Comment by yyxiongzju** [comment]
My email address is, yxiong43 at wisc.edu.

**Comment by RobertHua96** [comment]
Hi, wondering if this was progressing? Would love to experiment with the pretrained model from huggingface!

**Comment by novice03** [comment]
Nystromformer is now in huggingface: https://huggingface.co/docs/transformers/master/model_doc/nystromformer
